name: createmy_flutter_template
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  #package library
  core_component:
    path: ./modules/core_component
  theme: 
    path: ./modules/theme
  extensions: 
    path: ./modules/extensions
  test:
    path: ./test

  #system depends
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.1.0

  # state plugins  
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5

  #flutter depends
  flutter:
    sdk: flutter  

  #--mixed depends--
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  flutter_lints: ^2.0.0
  build_runner: 
  

flutter:
  uses-material-design: true
  assets:
    - assets/translations/lang/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
